server:
  port: 9191

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: department-service
          uri: lb://department-service
          predicates:
            - Path=/departments/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: 'true'
    register-with-eureka: 'true'
  server:
    peer-node-read-timeout-ms: '25000'
  instance:
    hostname: localhost

