server:
  port: 9191

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: user-service
                fallbackuri: forward:/getUserServiceFallbackMethod
        - id: department-service
          uri: lb://department-service
          predicates:
            - Path=/departments/**
          filters:
            - name: CircuitBreaker
              args:
                name: department-service
                fallbackuri: forward:/departmentServiceFallback

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: '4000'


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: 'true'
    register-with-eureka: 'true'
  server:
    peer-node-read-timeout-ms: '25000'
  instance:
    hostname: localhost

